version: "3.8"

services:
  frontend:
    build:
      context: ./front-end
    container_name: frontend-blog
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000/api/v1
      - PROJECT_ID="blog-site-be21f"
      - AUTH_DOMAIN= "Blog-site.firebaseapp.com"
      - API_KEY="AIzaSyD-9cb7koBnbWoQELGnysQn77nkKlAYOlM"


  backend:
    build:
      context: ./back-end
    container_name: backend-blog
    ports:
      - "5000:5000"
    working_dir: /app/src  # <--- Add this line
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/next-blog
      - PORT=5000
      - EMAILID=upalpatel1009@gmail.com
      - EMAIL_PASSWORD=zkalkevtguwgvjni
      - JWT_SECRET=helloguyswelcometoourblog

  mongo:
    image: mongo:latest
    container_name: mongo-blog
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db
